[startship]
config_file = "starship.toml"
path = "~/.config/starship.toml"

[git]
config_file = "gitconfig"
path = "~/.gitconfig"

[zsh]
config_file = "zshrc"
path = "~/.zshrc"

[vim]
config_file = "vimrc"
path = "~/.vimrc"
install = "git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"
